apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-sync-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: secret-sync-operator
  template:
    metadata:
      labels:
        name: secret-sync-operator
    spec:
      serviceAccountName: secret-sync-operator
      containers:
        - name: secret-sync-operator
          image: gableh/secret-sync-operator
          command:
          - secret-sync-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "secret-sync-operator"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
